# config/deploy.yml
service: server
image: slavenbg/nextjsvps
servers:
    # - <%= ENV["VPS_HOSTNAME"] %>
    - 64.23.210.216
registry:
    username:
        - KAMAL_REGISTRY_USERNAME
    password:
        - KAMAL_REGISTRY_PASSWORD
port: 3000
volumes:
    - 'data:/data'
